updated kubeadm_init playbook - deleted unncessary file

diff --git a/playbooks/roles/k8s/tasks/main.yml b/playbooks/roles/k8s/tasks/main.yml
--- a/playbooks/roles/k8s/tasks/main.yml
+++ b/playbooks/roles/k8s/tasks/main.yml
@@ -4,7 +4,7 @@
   get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docker-ce.repo
-  when: ansible_os_family == 'RedHat'
+  when: ansible_facts['os_family'] == 'RedHat'
 # ============================================================================ #
 - name: Install containerd.io and its dependecies
   package:
@@ -12,7 +12,7 @@
     state: present
   with_items:
   - containerd.io
-  when: ansible_os_family == 'RedHat'
+  when: ansible_facts['os_family'] == 'RedHat'
 # ============================================================================ #
 - name: Install containerd.io and its dependecies
   ansible.builtin.apt:
@@ -20,10 +20,12 @@
     state: present
   with_items:
   - containerd
-  when: ansible_os_family == 'Debian'
+  when: ansible_facts['os_family'] == 'Debian'
 # ============================================================================ #
 - name: Recreate containerd config file
-  shell: containerd config default > /etc/containerd/config.toml
+  shell: |
+    mkdir -p /etc/containerd
+    containerd config default > /etc/containerd/config.toml
 # ============================================================================ #
 - name: Enable cgroup for containerd
   register: containerd_cfg_out
@@ -41,46 +43,43 @@
 # ============================================================================ #
 - name: Add Kubernetes repository
   block:
-  - name: Add Kubernetes yum repository
-    become: yes
-    yum_repository:
-      name: Kubernetes
-      description: Kubernetes
-      baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
-      enabled: yes
-      gpgcheck: yes
-      gpgkey: 
-        - https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
-    when: ansible_os_family == 'RedHat'
+    - name: Add Kubernetes yum repository
+      become: yes
+      yum_repository:
+        name: Kubernetes
+        description: Kubernetes
+        baseurl: "https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/rpm/"
+        enabled: yes
+        gpgcheck: yes
+        gpgkey: 
+          - "https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/rpm/repodata/repomd.xml.key"
+      when: ansible_facts['os_family'] == 'RedHat'
 
-  - name: Add Kubernetes apt repository
-    block:
-      # - name: kubernetes repo gpg
-      #   ansible.builtin.get_url:
-      #     url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
-      #     dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
-      - name: Remove file (delete file)
-        ansible.builtin.file:
-          path: "{{ item }}"
-          state: absent
-        with_items:
-        - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
-        
-      - name: Kubernetes repo gpg
-        shell: |-
-          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+    - name: Remove old Kubernetes keyring
+      ansible.builtin.file:
+        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+        state: absent
+      when: ansible_facts['os_family'] == 'Debian'
 
-      - name: Kubernetes repo
-        ansible.builtin.apt_repository:
-          repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
-          state: present
-    when: ansible_os_family == 'Debian'
+    - name: Download Kubernetes GPG key
+      shell: |
+        curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/deb/Release.key | \
+        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+      args:
+        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
+      when: ansible_facts['os_family'] == 'Debian'
 
-  - name: Update apt cache
-    apt:
-      update_cache: yes
-    ignore_errors: yes
-    when: ansible_os_family == 'Debian'
+    - name: Add Kubernetes apt repository
+      ansible.builtin.apt_repository:
+        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/deb/ /"
+        state: present
+      when: ansible_facts['os_family'] == 'Debian'
+
+    - name: Update apt cache
+      apt:
+        update_cache: yes
+      ignore_errors: yes
+      when: ansible_facts['os_family'] == 'Debian'
 # ============================================================================ #
 - name: Install Kubernetes binaries
   package:
@@ -91,6 +90,15 @@
   - kubeadm
   - kubectl
 # ============================================================================ #
+- name: Hold Kubernetes packages
+  dpkg_selections:
+    name: "{{ item }}"
+    selection: hold
+  loop:
+    - kubeadm
+    - kubelet
+    - kubectl
+# ============================================================================ #
 - name: Ensure kubelet is started
   systemd:
     name: "{{ item }}"
@@ -98,3 +106,125 @@
     enabled: true
   with_items:
   - kubelet
+# ============================================================================ #
+- name: Init first cluster member
+  # Run this only on the first node in the inventory
+  when:
+    - inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+  changed_when: false
+  register: join_commands
+  shell: |-
+    kubeadm reset -f &&
+    #kubeadm init --v=5 \
+    #  --config=/etc/kubernetes/kubeadm_config.yaml \
+    #  --upload-certs \
+    #  &&
+    kubeadm init --v=5 --pod-network-cidr=192.168.0.0/16 --service-cidr=192.169.0.0/16 --upload-certs --control-plane-endpoint {{ ansible_host }}
+    true
+# ============================================================================ #
+  # - debug: var=join_commands
+- name: Retrieve join commands
+  set_fact:
+    join_command_control_plane:
+      "{{
+        ' '.join(join_commands.stdout_lines[-12:-8]).
+        replace('\\ ', '').
+        replace('\t', '').
+        strip()
+      }}"
+    join_command_worker:
+      "{{
+        ' '.join(join_commands.stdout_lines[-2:]).
+        replace('\\ ', '').
+        replace('\t', '').
+        strip()
+      }}"
+  when:
+    - join_commands is defined
+    - join_commands.stdout_lines is defined
+    - join_commands.stdout_lines[-1] != ''
+  delegate_to: "{{ item }}"
+  with_items: "{{ ansible_play_batch }}"
+  run_once: yes
+  # when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+- debug:
+    msg:
+      join_command_control_plane: "{{ join_command_control_plane }}"
+      join_command_worker: "{{ join_command_worker }}"
+  when:
+    - join_command_control_plane is defined
+    - join_command_worker is defined
+  # when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+- name: Join the other nodes to the cluster (Master)
+  shell: |-
+    kubeadm reset -f &&
+
+    {{ join_command_control_plane }} &&
+
+    true
+  when: 
+    - "'master' in group_names"
+    - inventory_hostname != hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+- name: Join the other nodes to the cluster (Slaves)
+  shell: |-
+    kubeadm reset -f &&
+    
+    {{ join_command_worker }} &&
+
+    true
+  when: "'worker' in group_names"
+# ============================================================================ #
+- name: Untaint control plane nodes
+  shell: |-
+    kubectl \
+      --kubeconfig /etc/kubernetes/admin.conf \
+      taint nodes --all \
+      node-role.kubernetes.io/control-plane- \
+      || true
+  when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+  # - name: Wait for nodes to become ready
+  #   when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+  #   shell: |-
+  #     kubectl \
+  #       --kubeconfig /etc/kubernetes/admin.conf \
+  #       get nodes |
+  #       awk '{print $2}' | tail -n +2 | uniq -c
+  #   register: control_plane_ready
+  #   retries: 10
+  #   delay: 10
+  #   until: control_plane_ready.stdout.strip().split() == [ HOST_COUNT | string , 'Ready']
+# ============================================================================ #
+- name: Get cluster info
+  when:
+    - inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+  ansible.builtin.shell: |-
+    kubectl \
+      --kubeconfig /etc/kubernetes/admin.conf \
+      cluster-info
+  register: cluster_info
+- debug: var=cluster_info.stdout
+  when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+- name: Label worker node
+  shell: |-
+    #!/bin/bash
+    set -x
+
+    export KUBECONFIG=/etc/kubernetes/admin.conf
+
+    for i in $(kubectl get nodes  | grep -v master | awk '{ print $1 }' | tail -n +2)
+    do
+      kubectl --kubeconfig /etc/kubernetes/admin.conf label node $i node-role.kubernetes.io/worker=true
+    done
+  when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
+# ============================================================================ #
+- name: Fetch kubeconfig file
+  ansible.builtin.fetch:
+    src: /etc/kubernetes/admin.conf
+    dest: ../admin.conf
+    flat: yes
+  when: inventory_hostname == hostvars[inventory_hostname].groups.all[0]
